export { default as Login } from './login'
export { default as Home } from './home'
export { default as TimeEntry } from './time-entry'
export { default as Dashboards } from './dashboards'
export {    default as HoursProvisioningReal} from './hoursProvisioningReal'
export { default as ProjectManagement } from './projectManagement'
export { default as Register } from './register'
export { default as HoursProvisioning } from './hoursProvisioning'
export { default as UserRegister } from './userRegister'
export { default as CustCenterRegister } from './custCenterRegister'
export { default as ProjectRegister } from './projectRegister'
export { default as ResourcesAllocation } from './resourcesAllocation'