export { default as Home } from './home'
export { default as One } from './one'
export { default as Two } from './two'
export { default as Three } from './three'
export { default as Four } from './four'
export { default as Login } from './login'
export { default as UserRegister} from './userRegister'
export { default as CustCenterRegister} from './custCenterRegister'
export { default as ProjectRegister} from './projectRegister'